version: "2"
services:
  ontario:
    image: kemele/ontario:0.3
    hostname: ontario
    container_name: ontario
    domainname: sdl
    volumes:
      - ./mappings:/mappings
      - ./configurations:/configurations
      - ./queries:/queries
      - ./results:/results
      - ./data/csv:/data/csv
    ports:
      - "5001:5000"
    environment:
      - CONFIG_FILE=/configurations/config.json
    restart: always
    networks:
      - osdl

  spain1:
    image: kemele/virtuoso:7-stable
    hostname: spain1rdf
    container_name: spain1
    domainname: sdl
    volumes:
      - ./data/rdf/spain:/data/toLoad
    ports:
      - "11385:8890"
      - "1116:1111"
    restart: always
    networks:
      - osdl
  spain2:
    image: kemele/virtuoso:7-stable
    hostname: spain2rdf
    container_name: spain2
    domainname: sdl
    volumes:
      - ./data/rdf/spain:/data/toLoad
    ports:
      - "11386:8890"
      - "1116:1111"
    restart: always
    networks:
      - osdl
  spain3:
    image: kemele/virtuoso:7-stable
    hostname: spain3rdf
    container_name: spain3
    domainname: sdl
    volumes:
      - ./data/rdf/spain:/data/toLoad
    ports:
      - "11387:8890"
      - "1116:1111"
    restart: always
    networks:
      - osdl  
  spain4:
    image: kemele/virtuoso:7-stable
    hostname: spain4rdf
    container_name: spain4
    domainname: sdl
    volumes:
      - ./data/rdf/spain:/data/toLoad
    ports:
      - "11388:8890"
      - "1116:1111"
    restart: always
    networks:
      - osdl  
  spain5:
    image: kemele/virtuoso:7-stable
    hostname: spain5rdf
    container_name: spain5
    domainname: sdl
    volumes:
      - ./data/rdf/spain:/data/toLoad
    ports:
      - "11389:8890"
      - "1116:1111"
    restart: always
    networks:
      - osdl
  spain6:
    image: kemele/virtuoso:7-stable
    hostname: spain6rdf
    container_name: spain6
    domainname: sdl
    volumes:
      - ./data/rdf/spain:/data/toLoad
    ports:
      - "11390:8890"
      - "1116:1111"
    restart: always
    networks:
      - osdl      


  belgium1:
    image: kemele/virtuoso:7-stable
    hostname: belgium1rdf
    container_name: belgium1
    domainname: sdl
    volumes:
      - ./data/rdf/belgium:/data/toLoad
    ports:
      - "11391:8890"
      - "1117:1111"
    restart: always
    networks:
      - osdl
  belgium2:
    image: kemele/virtuoso:7-stable
    hostname: belgium2rdf
    container_name: belgium2
    domainname: sdl
    volumes:
      - ./data/rdf/belgium:/data/toLoad
    ports:
      - "11392:8890"
      - "1117:1111"
    restart: always
    networks:
      - osdl
  belgium3:
    image: kemele/virtuoso:7-stable
    hostname: belgium3rdf
    container_name: belgium3
    domainname: sdl
    volumes:
      - ./data/rdf/belgium:/data/toLoad
    ports:
      - "11393:8890"
      - "1117:1111"
    restart: always
    networks:
      - osdl
  belgium4:
    image: kemele/virtuoso:7-stable
    hostname: belgium4rdf
    container_name: belgium4
    domainname: sdl
    volumes:
      - ./data/rdf/belgium:/data/toLoad
    ports:
      - "11394:8890"
      - "1117:1111"
    restart: always
    networks:
      - osdl
  belgium5:
    image: kemele/virtuoso:7-stable
    hostname: belgium5rdf
    container_name: belgium5
    domainname: sdl
    volumes:
      - ./data/rdf/belgium:/data/toLoad
    ports:
      - "11395:8890"
      - "1117:1111"
    restart: always
    networks:
      - osdl
  belgium6:
    image: kemele/virtuoso:7-stable
    hostname: belgium6rdf
    container_name: belgium6
    domainname: sdl
    volumes:
      - ./data/rdf/belgium:/data/toLoad
    ports:
      - "11396:8890"
      - "1117:1111"
    restart: always
    networks:
      - osdl                        
networks:
  osdl:
    external: false
